language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "pypy"
before_install:
  - export PIP_DOWNLOAD_CACHE=$HOME/.pip-cache
  - pip install pep8
install:
  - python setup.py install
script:
  - nosetests -v
  - pyflakes *.py
  - pep8 *.py
